export const lightTheme = {
  background: '#F4F7F6',
  text: '#333',
  headerText: '#fff',
  cardBackground: '#fff',
  buttonBackground: '#4A90E2',
  buttonText: '#fff',
  inputBackground: '#F4F7F6',
  inputText: '#333',
  placeholder: '#999',
  checkboxActive: '#4A90E2',
  checkboxInactive: '#ccc',
  subtext: '#666', 
  cancelButtonBackground: '#FF6347', 
};

export const darkTheme = {
  background: '#121212',
  text: '#E0E0E0',
  headerText: '#E0E0E0',
  cardBackground: '#1E1E1E',
  buttonBackground: '#BB86FC',
  buttonText: '#121212',
  inputBackground: '#1E1E1E',
  inputText: '#E0E0E0',
  placeholder: '#999',
  checkboxActive: '#BB86FC',
  checkboxInactive: '#666',
  subtext: '#B0B0B0', 
  cancelButtonBackground: '#CF6679', 
};
